Task_Totali/ASP/Task_Palestra+Video/ASP_Palestra_Task/ASP_Palestra_Task/Models/Iscrizione.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace ASP_Palestra_Task.Models
{
    public partial class Iscrizione
    {
        [Key]
        public int IscrizioneID { get; set; }

        public DateTime DataIscrizione { get; set; }
        [ForeignKey("corsoRIF")]
        public int CorsoRif { get; set; }
        [ForeignKey("utenteRIF")]
        public int UtenteRif { get; set; }

        public virtual Corso CorsoRifNavigation { get; set; }
        public virtual Utente UtenteRifNavigation { get; set; }

        public Iscrizione()
        {
            DataIscrizione = DateTime.Now;
        }
    }
}

Task_Totali/ASP/Task_Palestra+Video/ASP_Palestra_Task/ASP_Palestra_Task/ViewModels/IscrizioneViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Palestra_Task.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP_Palestra_Task.ViewModels
{
    public class IscrizioneViewModel
    {
        public Utente UtenteLogged { get; set; }

        public List<Corso> Corsi { get; set; }

        public Iscrizione Iscrizione { get; set; }

        public List<Iscrizione> Iscrizioni { get; set; }
    }
}

Task_Totali/ASP/Task_Palestra+Video/ASP_Palestra_Task/ASP_Palestra_Task/Controllers/IscrizioneController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Palestra_Task.Data;
using ASP_Palestra_Task.Models;
using ASP_Palestra_Task.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP_Palestra_Task.Controllers
{
    public class IscrizioneController : Controller
    {
        private readonly IIscrizioneRepository _repoIscr;
        private readonly IUtenteRepository _repoUser;

        public IscrizioneController(IIscrizioneRepository repoIscr, IUtenteRepository repoUser)
        {
            _repoUser = repoUser;
            _repoIscr = repoIscr;
        }

        [HttpGet]
        public IActionResult IscrizioneCorso()
        {
            string username = HttpContext.Session.GetString("IsLogged");
            ViewData["User"] = username;
            if (username == null)
                return Redirect("/Home/LogIn");

            Utente loggato = _repoUser.GetByUsername(username);
            List<Corso> corsi = _repoIscr.GetAllCorsi().ToList();

            _repoIscr.GetCorsiByUser(loggato.UtenteId).ToList().ForEach(i =>
            {
                if (corsi.Contains(i)) corsi.Remove(i);
            });
            return View(new IscrizioneViewModel { Corsi = corsi, UtenteLogged = loggato });
        }

        
        public IActionResult Iscrizione([FromRoute]int id)
        {
            string username = HttpContext.Session.GetString("IsLogged");
            ViewData["User"] = username;
            if (username == null)
                return Redirect("/Home/LogIn");

            Utente loggato = _repoUser.GetByUsername(username);
            Iscrizione iscriz = new Iscrizione
            {
                CorsoRif = id,
                UtenteRif = loggato.UtenteId
            };
            _repoIscr.Insert(iscriz);

            return RedirectToAction("IscrizioneCorso");
        }

        [HttpGet]
        public IActionResult AreaPersonale()
        {
            string username = HttpContext.Session.GetString("IsLogged");
            ViewData["User"] = username;
            if (username == null)
                return Redirect("/Home/LogIn");

            Utente loggato = _repoUser.GetByUsername(username);
            List<Iscrizione> iscrizioni = _repoIscr.GetAll().Where(i => i.UtenteRif == loggato.UtenteId).ToList();

            return View(new IscrizioneViewModel { Iscrizioni = iscrizioni, UtenteLogged = loggato });
        }

        public IActionResult Cancella([FromRoute]int id)
        {
            string username = HttpContext.Session.GetString("IsLogged");
            ViewData["User"] = username;
            if (username == null)
                return Redirect("/Home/LogIn");

            Iscrizione iscr = _repoIscr.GetById(id);
            _repoIscr.Delete(iscr);
            return RedirectToAction("AreaPersonale");
        }
    }
}

Task_Totali/ASP/Task_Palestra+Video/ASP_Palestra_Task/ASP_Palestra_Task/Views/Iscrizione/AreaPersonale.cshtml
@using ASP_Palestra_Task.Models
@model ASP_Palestra_Task.ViewModels.IscrizioneViewModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Area Personale";
}

<div class="row">
    <div class="col-md-4 mt-5 bg-dark rounded text-white p-3">
        <h4>Username(Email):</h4>
            <h6>@Model.UtenteLogged.Username</h6>
            <h4 class="text">Nome:</h4>
            <h6>@Model.UtenteLogged.Nome</h6>
            <h4>Cognome:</h4>
            <h6>@Model.UtenteLogged.Cognome</h6>
             <h4>Indirizzo:</h4>
            <h6>@Model.UtenteLogged.Indirizzo</h6>
            <h4>Data di nascita:</h4>
            <h6>@Model.UtenteLogged.DataNascita.ToShortDateString()</h6>
    </div>
    <div class="col-md-8 mt-5">
        @if (Model.Iscrizioni.Count != 0)
        {
            <div class="list-group scrollbar scrollbar-info">
                <div class="force-overflow">
                    @foreach (Iscrizione item in Model.Iscrizioni)
                    {
                        <div class="list-group-item bg-dark text-white">
                            <div class="d-flex w-100 justify-content-between mb-2">
                                <h4>@item.CorsoRifNavigation.Titolo</h4>
                                <small class="text-muted">@item.DataIscrizione.ToShortDateString()</small>
                            </div>
                            <p class="mb-1">@item.CorsoRifNavigation.Descrizione</p>
                            <div class="text-right">
                                <a class="btn btn-outline-danger btn-sm" asp-controller="Iscrizione" asp-action="Cancella" asp-route-id="@item.IscrizioneID">Annulla Iscrizione</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
        else
        {
            <div class="alert alert-dark text-center">
                <h3>Non sei iscritto a nessun corso!</h3>
            </div>
        }
    </div>
</div>

Task_Totali/ASP/Task_Palestra+Video/ASP_Palestra_Task/ASP_Palestra_Task/Views/Iscrizione/IscrizioneCorso.cshtml
@using ASP_Palestra_Task.Models
@model ASP_Palestra_Task.ViewModels.IscrizioneViewModel
@{
    ViewData["Title"] = "Iscrizione al Corso";
    Layout = "_Layout";
}

<div class="row mt-5">
    <div class="col-md form-row justify-content-md-around">
        @if (Model.Corsi.Count != 0)
        {
            foreach (var item in @Model.Corsi)
            {
                <div class="card mb-5 bg-dark text-white" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@item.Titolo</h5>
                        <p class="card-text">@item.Descrizione</p>
                        <footer> Data: @item.DataInizio.ToShortDateString() - @item.DataFine.ToShortDateString()</footer>
                        <footer class="mb-2">Orario: @item.OraInizio - @item.OraFine</footer>
                        <a asp-action="Iscrizione" asp-route-id="@item.CorsoId" class="btn btn-outline-success">Iscriviti</a>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="alert alert-success mt-3">
                <h2>Sei iscritto a tutti i corsi</h2>
            </div>
        }
    </div>
</div>